#!/usr/bin/env python3

import os
import docker

from threading import Thread
from time import sleep
from simple_term_menu import TerminalMenu


client = docker.from_env()
selected_container_id = None
log_printing_status = 'visible'
search = None


def search_input():
    global log_printing_status, search

    container = client.containers.get(container_id=selected_container_id)

    input()

    log_printing_status = 'hidden'
    os.system('clear')

    print(f'> \x1B[92mCONTAINER:\x1B[0m {container.name}')
    search = input('> \x1B[93mEnter filter:\x1B[0m ').strip()

    if not search:
        search = None

    log_printing_status = 'visible'


def logs_viewer(container_id):
    global search

    try:
        while True:
            if log_printing_status != 'visible':
                sleep(0.1)
                continue

            os.system('clear')
            container = client.containers.get(container_id=container_id)

            if search:
                search_visible_text = search
                search_variants = search.split('||')
            else:
                search_visible_text = '\x1B[94m<all>\x1B[0m'
                search_variants = []

            print(f'> \x1B[92mCONTAINER:\x1B[0m {container.name}')
            print(f'> \x1B[92mFILTER:\x1B[0m {search_visible_text} \x1B[93m[ENTER to change]\x1B[0m')

            for line in container.logs(stream=True, tail=1000):
                if log_printing_status != 'visible':
                    break

                log_text = line.decode("utf-8").strip()

                if (
                    not search_variants or
                    any(search_variant in log_text for search_variant in search_variants)
                ):
                    print(log_text)

    except (KeyboardInterrupt, Exception):
        pass


if __name__ == "__main__":
    try:
        os.system('clear')

        container_names = []
        containers = {}

        for c in client.containers.list():
            container_names.append(c.name)
            containers[c.name] = c

        terminal_menu = TerminalMenu(
            container_names,
            title="Select container:"
        )
        selected_container_id = containers[container_names[terminal_menu.show()]].id

        Thread(target=logs_viewer, args=(selected_container_id,), daemon=True).start()

        while True:
            search_input()

    except (KeyboardInterrupt, Exception):
        pass
